name: API CI
on: push

env:
  POSTGRES_USER: sample_admin
  POSTGRES_PASSWORD: sample_psql
  POSTGRES_PORT: 5555
  POSTGRES_DB: sample_test
  DATABASE_URL: 'postgresql://sample_admin:sample_psql@localhost:5555/sample_test?schema=public'
  NODE_ENV: 'test'

jobs:
  build_and_test:
    name: Test before merging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: cache-node-modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: package-install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: pnpm install
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Storage init
        id: storage_init
        run: pnpm storage:init
      - name: Generate
        run: pnpm prisma generate
      - name: Migrate
        id: prisma_migrate
        run: pnpm prisma migrate deploy
      - name: Test
        id: test
        run: pnpm test:ci
      - name: pnpm tsc
        id: pnpm_tsc
        run: pnpm tsc
