name: ER Diagram

on:
  pull_request:
    paths:
      - '.github/workflows/check-erd.yml'
      - 'prisma/**'

jobs:
  check:
    name: Check ERD Diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: cache-node-modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: package-install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: pnpm install
      - name: makeERD
        run: pnpm erd
      - id: checkErdDiff
        run: echo "changed=$(git diff --name-only prisma/ERD.md)" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.checkErdDiff.outputs.changed}}
      - if: ${{ steps.checkErdDiff.outputs.changed != '' }}
        run: |
          echo "ERD.md has changed.Please update ERD.md and commit it."
          exit 1
