name: React-CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup-node
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: 'pnpm'
      - name: cache-node-modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: package-install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: pnpm install
      - name: eslint-check
        run: pnpm lint
      - name: prettier-check
        run: pnpm fmt:check
      - name: build
        run: pnpm build
